# Generated by Django 2.1.3 on 2018-11-22 06:06

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone
import filebrowser.fields
import meta.models
import model_utils.fields
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialNewsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'тип коммерческих новостей',
                'verbose_name_plural': 'типы коммерческих новостей',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(db_index=True, default=False, help_text='Статус чернеовика', verbose_name='Показывать на сайте?')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('seo_title', models.CharField(blank=True, help_text='* !! НЕ обязательное поле, можно оставить пустым!', max_length=255, null=True, verbose_name='Заголовок(SEO)')),
                ('seo_meta', models.TextField(blank=True, help_text='Мета-описание страницы для сниппета', null=True, verbose_name='Meta(SEO)')),
                ('seo_keywords', models.TextField(blank=True, help_text='* !! НЕ обязательное поле, можно оставить пустым!', null=True, verbose_name='Ключи')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('slug', models.SlugField(blank=True, help_text='Можно оставлять пустып, авто из названия будет', max_length=75, null=True, verbose_name='URL')),
                ('dt_mod', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата пибликации')),
                ('image', filebrowser.fields.FileBrowseField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Фото')),
                ('on_main_page', models.BooleanField(db_index=True, default=False, verbose_name='На главную')),
                ('commercial', models.BooleanField(db_index=True, default=False, verbose_name='Комерческая новость')),
                ('show_count', models.IntegerField(db_index=True, default=0, verbose_name='Количество показов')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'ordering': ('-dt_mod',),
            },
            bases=(meta.models.ModelMeta, models.Model),
            managers=[
                ('publish', django.db.models.manager.Manager()),
            ],
        ),
    ]
