# Generated by Django 2.1.3 on 2018-11-22 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='dt_mod',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Дата пибликации'),
        ),
    ]
