# Generated by Django 2.1.3 on 2018-11-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20181122_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source_audio',
            field=models.FileField(blank=True, help_text='*.mp3', null=True, upload_to='', verbose_name='Аудио-файл'),
        ),
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[[1, 'Официально'], [2, 'Видео'], [3, 'Аудио'], [4, 'Наука'], [5, 'Технологии'], [6, 'Lifestyle']], db_index=True, default=1, verbose_name='Тип контента'),
        ),
        migrations.AddField(
            model_name='news',
            name='url_video',
            field=models.FileField(blank=True, help_text='Ссылка на видео с youtube', null=True, upload_to='', verbose_name='Видео с YouTube'),
        ),
        migrations.AlterField(
            model_name='news',
            name='commercial',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Коммерческая новость'),
        ),
    ]
