
# TINYMCE_COMPRESSOR = False
TINYMCE_DEFAULT_CONFIG = {
    'plugins': "safari,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,asciimath",
    'theme': "advanced",
    'language': "ru",
    'content_css': "/static/css/tinymce.css",
    'visualblocks_default_state': "true",
    # Schema is HTML5 instead of default HTML4
    'schema': "html5",
    # 'valid_elements' : "",
    'style_formats_merge': "true",
    'extended_valid_elements' : "mark",
    'style_formats': [
        # {'title': u'Под катом', 'block': 'div','classes': 'b-cut'},
        # {'title': u'Файл .doc', 'inline' : 'span', 'classes' : 'b-file-extension_type_doc'},
        # {'title': u'Файл .xls', 'inline' : 'span', 'classes' : 'b-file-extension_type_xls'},
        # {'title': u'Файл .pdf', 'inline' : 'span', 'classes' : 'b-file-extension_type_pdf'},
        # {'title': u'Файл .ppt', 'inline' : 'span', 'classes' : 'b-file-extension_type_ppt'},
        # {'title': u'Файл .rar', 'inline' : 'span', 'classes' : 'b-file-extension_type_rar'},
        # {'title': u'Файл .zip', 'inline' : 'span', 'classes' : 'b-file-extension_type_zip'},
        {'title': u'Резиновая картинка', 'inline' : 'span', 'classes' : 'img-responsive'},
        {'title': u'Ключевик', 'inline' : 'mark', 'exact': 'false' },
        {'title': u'Круглая кнопка', 'selector': 'a', 'classes' : 'btn btn-sm btn-default btn-rounded'},
        {'title': u'Текст margin-b-15', 'selector': 'p', 'classes' : 'm-b-15'},
        {'title': u'Текст info', 'selector': 'p', 'classes' : 'text-info'},
        {'title': u'Текст warning', 'selector': 'p', 'classes' : 'text-warning'},
        {'title': u'Текст danger', 'selector': 'p', 'classes' : 'text-danger'},
        {'title': u'Текст text-right', 'selector': 'p,h1,h2,h3,h4', 'classes' : 'text-right'},
        {'title': u'Текст text-center', 'selector': 'p,h1,h2,h3,h4', 'classes' : 'text-center'},
        {'title': u'Текст text-justify', 'selector': 'p,h1,h2,h3,h4', 'classes' : 'text-justify'},
        # {'title': u'button-3d', 'selector': 'a', 'classes' : 'button button-default button-3d full-rounded'},

    ],
    'theme_advanced_buttons1': "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,|,styleselect,formatselect",
    'theme_advanced_buttons2': "cut,copy,paste,pasteword,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,code,|,forecolor,backcolor",
    'theme_advanced_buttons3': "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,iespell,media,advhr,asciimathcharmap,|,fullscreen",
    'theme_advanced_toolbar_location': "top",
    'theme_advanced_toolbar_align': "left",
    'theme_advanced_statusbar_location': "bottom",
    'theme_advanced_resizing': "false",
    'function' : 'function(e) {e.onGetContent.add(function(e, o) {o.content = o.content.replace(/<span\ class="mark"[^>]*>([^>]+)<\/span>/ig,"<mark>$1</mark>");});',
    'AScgiloc': "http://www.imathas.com/editordemo/php/svgimg.php",
    'ASdloc': "%stiny_mce/plugins/asciisvg/js/d.svg" % (BASE_DIR + STATIC_URL),
    #'convert_newlines_to_brs' : "true",
    #'paste_auto_cleanup_on_paste' : "true",
    #'paste_remove_spans' : "true",
    # 'paste_remove_styles' : "true",
    #'paste_strip_class_attributes' : "none",
    #'paste_retain_style_properties' : "none",
}
